import type { DocumentTemplate } from '../types';

export const DEFAULT_DOCUMENT_TEMPLATE: DocumentTemplate = {
  version: 2,
  branding: {
    primary_color: '#1e40af',
    secondary_color: '#374151',
    accent_color: '#059669',
    font_family: 'helvetica',
    header_bg_color: null,
    header_text_color: '#1e40af',
    table_header_bg: '#1e40af',
    table_header_text: '#ffffff',
    table_row_alt_bg: '#f9fafb',
    border_color: '#e5e7eb',
    price_highlight_color: '#059669',
  },
  content_blocks: [
    {
      id: 'default_measurement',
      type: 'measurement_item',
      role: 'calculavel',
      title: 'Produto',
      fields: [
        { key: 'product_name', label: 'Produto', type: 'text', visible: true },
        { key: 'area', label: 'Área (m²)', type: 'area', visible: true },
        { key: 'preco_m2', label: 'Valor/m²', type: 'currency', visible: true },
        { key: 'total', label: 'Total', type: 'currency', visible: true },
        { key: 'discount_price', label: 'À Vista', type: 'currency', visible: true },
      ],
      calculation: { formula: 'area * preco_m2', explicit: true },
      confidence: 1,
      style: {
        display: 'card',
        background_color: null,
        border: true,
        title_font_size: 11,
        body_font_size: 10,
      },
    },
  ],
  company_fields: [],
  client_fields: [
    { label: 'Cliente:', type: 'cliente_nome', required: true },
    { label: 'Telefone:', type: 'cliente_telefone', required: false },
    { label: 'Endereço:', type: 'endereco_completo', required: false },
    { label: 'Serviço:', type: 'tipo_servico', required: true },
    { label: 'Data:', type: 'data', required: true },
  ],
  budget_table: {
    columns: [
      { key: 'option_number', label: 'Opção', width_percent: 8, align: 'center' },
      { key: 'product_name', label: 'Produto', width_percent: 32, align: 'left' },
      { key: 'area', label: 'Área (m²)', width_percent: 12, align: 'right' },
      { key: 'unit_price', label: 'Valor/m²', width_percent: 15, align: 'right' },
      { key: 'total', label: 'Total', width_percent: 15, align: 'right' },
      { key: 'discount_price', label: 'À Vista', width_percent: 18, align: 'right' },
    ],
    style: 'cards',
    show_header: true,
    show_borders: true,
    row_padding: 6,
    header_font_size: 10,
    body_font_size: 10,
  },
  totals: {
    show_discount: true,
    discount_label: 'À VISTA (5% desc.):',
    discount_percent: 5,
    show_installments: true,
    installment_label: 'Parcelado:',
    position: 'per_item',
  },
  observations: {
    default_text: 'Orçamento válido por 15 dias. Medidas devem ser confirmadas no local. Valores sujeitos a alteração sem aviso prévio.',
    position: 'bottom',
    style: 'italic',
    font_size: 8,
  },
  layout_metadata: {
    page_size: 'a4',
    orientation: 'portrait',
    margins: { top: 15, right: 15, bottom: 15, left: 15 },
    header: {
      height: 40,
      logo_position: 'left',
      logo_max_height: 25,
      company_info_position: 'right',
      title: { text: 'ORÇAMENTO', alignment: 'center', font_size: 18 },
      background_color: null,
      show_separator: true,
      separator_color: '#1e40af',
    },
    sections_order: ['header', 'client', 'content_blocks', 'observations', 'footer'],
    section_spacing: 8,
    client_section: {
      style: 'inline',
      background_color: null,
      border: false,
      border_color: null,
      label_bold: true,
      label_font_size: 10,
      value_font_size: 10,
    },
    footer: {
      style: 'line',
      separator_color: '#e5e7eb',
      text_alignment: 'center',
      font_size: 8,
      text_color: '#9ca3af',
    },
  },
};
